#!/bin/bash
# rename_audio.sh
# Renames existing MP3 files in data/rio_grande_rift/audio/ to match the
# new sequential numbering after 7 POIs were inserted into scripts.json.
# Renamed from HIGHEST to LOWEST to avoid overwrite collisions.
# New POIs (03, 05, 27, 30, 32, 36, 44) will be generated by generate_audio.py.

AUDIO_DIR="data/rio_grande_rift/audio"
cd "$(dirname "$0")" || exit 1

echo "Renaming audio files in $AUDIO_DIR ..."

# Rename from highest to lowest
mv "$AUDIO_DIR/52.mp3" "$AUDIO_DIR/59.mp3" && echo "52 → 59"
mv "$AUDIO_DIR/51.mp3" "$AUDIO_DIR/58.mp3" && echo "51 → 58"
mv "$AUDIO_DIR/50.mp3" "$AUDIO_DIR/57.mp3" && echo "50 → 57"
mv "$AUDIO_DIR/49.mp3" "$AUDIO_DIR/56.mp3" && echo "49 → 56"
mv "$AUDIO_DIR/48.mp3" "$AUDIO_DIR/55.mp3" && echo "48 → 55"
mv "$AUDIO_DIR/47.mp3" "$AUDIO_DIR/54.mp3" && echo "47 → 54"
mv "$AUDIO_DIR/46.mp3" "$AUDIO_DIR/53.mp3" && echo "46 → 53"
mv "$AUDIO_DIR/45.mp3" "$AUDIO_DIR/52.mp3" && echo "45 → 52"
mv "$AUDIO_DIR/44.mp3" "$AUDIO_DIR/51.mp3" && echo "44 → 51"
mv "$AUDIO_DIR/43.mp3" "$AUDIO_DIR/50.mp3" && echo "43 → 50"
mv "$AUDIO_DIR/42.mp3" "$AUDIO_DIR/49.mp3" && echo "42 → 49"
mv "$AUDIO_DIR/41.mp3" "$AUDIO_DIR/48.mp3" && echo "41 → 48"
mv "$AUDIO_DIR/40.mp3" "$AUDIO_DIR/47.mp3" && echo "40 → 47"
mv "$AUDIO_DIR/39.mp3" "$AUDIO_DIR/46.mp3" && echo "39 → 46"
mv "$AUDIO_DIR/38.mp3" "$AUDIO_DIR/45.mp3" && echo "38 → 45"
# 44 is new (37b Taos Pueblo) — will be generated
mv "$AUDIO_DIR/37.mp3" "$AUDIO_DIR/43.mp3" && echo "37 → 43"
mv "$AUDIO_DIR/36.mp3" "$AUDIO_DIR/42.mp3" && echo "36 → 42"
mv "$AUDIO_DIR/35.mp3" "$AUDIO_DIR/41.mp3" && echo "35 → 41"
mv "$AUDIO_DIR/34.mp3" "$AUDIO_DIR/40.mp3" && echo "34 → 40"
mv "$AUDIO_DIR/33.mp3" "$AUDIO_DIR/39.mp3" && echo "33 → 39"
mv "$AUDIO_DIR/32.mp3" "$AUDIO_DIR/38.mp3" && echo "32 → 38"
mv "$AUDIO_DIR/31.mp3" "$AUDIO_DIR/37.mp3" && echo "31 → 37"
# 36 is new (30b Santa Fe) — will be generated
mv "$AUDIO_DIR/30.mp3" "$AUDIO_DIR/35.mp3" && echo "30 → 35"
mv "$AUDIO_DIR/29.mp3" "$AUDIO_DIR/34.mp3" && echo "29 → 34"
mv "$AUDIO_DIR/28.mp3" "$AUDIO_DIR/33.mp3" && echo "28 → 33"
# 32 is new (27b Coronado) — will be generated
mv "$AUDIO_DIR/27.mp3" "$AUDIO_DIR/31.mp3" && echo "27 → 31"
# 30 is new (26b Peoples of the Rio Grande) — will be generated
mv "$AUDIO_DIR/26.mp3" "$AUDIO_DIR/29.mp3" && echo "26 → 29"
mv "$AUDIO_DIR/25.mp3" "$AUDIO_DIR/28.mp3" && echo "25 → 28"
# 27 is new (24b Green Chile Burger) — will be generated
mv "$AUDIO_DIR/24.mp3" "$AUDIO_DIR/26.mp3" && echo "24 → 26"
mv "$AUDIO_DIR/23.mp3" "$AUDIO_DIR/25.mp3" && echo "23 → 25"
mv "$AUDIO_DIR/22.mp3" "$AUDIO_DIR/24.mp3" && echo "22 → 24"
mv "$AUDIO_DIR/21.mp3" "$AUDIO_DIR/23.mp3" && echo "21 → 23"
mv "$AUDIO_DIR/20.mp3" "$AUDIO_DIR/22.mp3" && echo "20 → 22"
mv "$AUDIO_DIR/19.mp3" "$AUDIO_DIR/21.mp3" && echo "19 → 21"
mv "$AUDIO_DIR/18.mp3" "$AUDIO_DIR/20.mp3" && echo "18 → 20"
mv "$AUDIO_DIR/17.mp3" "$AUDIO_DIR/19.mp3" && echo "17 → 19"
mv "$AUDIO_DIR/16.mp3" "$AUDIO_DIR/18.mp3" && echo "16 → 18"
mv "$AUDIO_DIR/15.mp3" "$AUDIO_DIR/17.mp3" && echo "15 → 17"
mv "$AUDIO_DIR/14.mp3" "$AUDIO_DIR/16.mp3" && echo "14 → 16"
mv "$AUDIO_DIR/13.mp3" "$AUDIO_DIR/15.mp3" && echo "13 → 15"
mv "$AUDIO_DIR/12.mp3" "$AUDIO_DIR/14.mp3" && echo "12 → 14"
mv "$AUDIO_DIR/11.mp3" "$AUDIO_DIR/13.mp3" && echo "11 → 13"
mv "$AUDIO_DIR/10.mp3" "$AUDIO_DIR/12.mp3" && echo "10 → 12"
mv "$AUDIO_DIR/09.mp3" "$AUDIO_DIR/11.mp3" && echo "09 → 11"
mv "$AUDIO_DIR/08.mp3" "$AUDIO_DIR/10.mp3" && echo "08 → 10"
mv "$AUDIO_DIR/07.mp3" "$AUDIO_DIR/09.mp3" && echo "07 → 09"
mv "$AUDIO_DIR/06.mp3" "$AUDIO_DIR/08.mp3" && echo "06 → 08"
mv "$AUDIO_DIR/05.mp3" "$AUDIO_DIR/07.mp3" && echo "05 → 07"
mv "$AUDIO_DIR/04.mp3" "$AUDIO_DIR/06.mp3" && echo "04 → 06"
# 05 is new (3b Mission Trail intro) — will be generated
mv "$AUDIO_DIR/03.mp3" "$AUDIO_DIR/04.mp3" && echo "03 → 04"
# 03 is new (1b Franklin Mountains) — will be generated
mv "$AUDIO_DIR/02.mp3" "$AUDIO_DIR/03.mp3" && echo "02 → 03"
# 01 and 02 unchanged — 01 stays, 02 just moved above

echo ""
echo "Done renaming. Remaining files:"
ls "$AUDIO_DIR"/*.mp3 | sort
echo ""
echo "Missing (new POIs to generate): 02.mp3 05.mp3 27.mp3 30.mp3 32.mp3 36.mp3 44.mp3"
echo "Run: source .venv/bin/activate && python src/generate_audio.py --force rio_grande_rift"
